### ISSUE TITLE
UI-Router corrections

### ISSUE THREAD

**Issue by nateabele** [jmeas/router-comparison#22]
Re: https://twitter.com/jmeaspls/status/630456361164390400

> UI-Router came a few months later, and shares some similarities to Ember Router, but also has some unique features.

There are similarities by virtue of the fact that both model a hierarchical state machine, but a lot of that was based on my prior routing work in server-side frameworks. None of the core contributors really looked at Ember until UI-Router's architecture was already fairly well-established.

> Optional segments

We have them, they're just not part of the DSL. See https://github.com/angular-ui/ui-router/blob/master/test/urlMatcherFactorySpec.js#L585

> Regex instead of DSL

You can absolutely do this in UI-Router. Everything compiles down to object-wrapped regexes anyway. In fact, you can implement completely arbitrary objects to parse and format URLs, so long as they conform to the `URLMatcher` interface.

> Reset Namespace

I take this to mean that a child state is not required to have the URL of the parent state prefixed onto it? UI-Router supports this as well: https://github.com/angular-ui/ui-router/wiki/URL-Routing#absolute-routes-

> A friend of mine on the Ember Data team suggests that nobody use this feature, which is pretty telling, I think.

We have users with pretty sophisticated state trees that do this all the time. It provides for a lot of flexibility in terms of breaking the direct relationship between states and URLs. If Ember developers say Ember users don't use it, this could just as easily be a function of the default level of expressiveness of the system vs. rigorous conventions.

> Includes history

Marking UI-Router off for this doesn't really make sense...

> In UI-Router and Stateman, an event is fired on the router itself that allows you to cancel the transition, so it's more like a global setting.

Our alpha version (due out shortly) allows transitions to be canceled, postponed, or redirected at any level of granularity.

> `.active` links

We do support this, we just consider it bad practice to hard-code it to the link itself. See code examples here: https://angular-ui.github.io/ui-router/site/#/api/ui.router.state.directive:ui-sref-active

> 'Error' states
> 'Not Found' states

We just use events for these. Again, hard-coding these behaviors to specific states is something we consider bad practice, since you may want to vary the behavior by what triggers it. For example, our 'not found' event allows you to asynchronously hot-load states before resuming the transition.

> Group data fetching

The alpha version allows specification of different 'policies' for this.

> Update hook

This use case is covered by parameter observers. Combined with type definitions (i.e.`Book` in your example), you can encapsulate resource loading and data updating in a much more focused way than is possible with an arbitrary hook.

**Comment by jamesplease** [comment]
@nateabele, thanks so much for going through this huge doc! I really appreciate it.

> There are similarities by virtue of the fact that both model a hierarchical state machine, but a lot of that was based on my prior routing work in server-side frameworks. None of the core contributors really looked at Ember until UI-Router's architecture was already fairly well-established.

I had a sense that this was the case, but I wasn't sure, so I tried to keep it semi-ambiguous. I'll update the wording to make this more clear.

> We have them, they're just not part of the DSL.

Very interesting! Is it the curly braces that mark it as optional? I wasn't able to discern this behavior based on [the API docs on the website](http://angular-ui.github.io/ui-router/site/#/api/ui.router.util.type:UrlMatcher), which state the following facts:

> '/user/:id' - Matches '/user/bob' or '/user/1234!!!' or even '/user/' but not '/user' or '/user/bob/details'. The second path segment will be captured as the parameter 'id'.
> '/user/{id}' - Same as the previous example, but using curly brace syntax.

Maybe I'm missing something obvious, though? :see_no_evil: 

> You can absolutely do this in UI-Router.

My mistake. I'll update this.

> Marking UI-Router off for this doesn't really make sense...

I wouldn't think of any given X as a necessarily bad thing. It's not about including **every feature** – some are redundant or provide little value, I think.

On the subject of history: if I read the src correctly, it seems that the UI-Router uses a history implementation already provided by Angular, so, technically, it (luckily) does not include a duplicate implementation. That's a good thing, right?

Though, maybe you're right that it makes more sense to give it a check with an asterisk, since it's not like you need to bring your own history to work with UI-Router. I'll make the change.

> Our alpha version (due out shortly) allows transitions to be canceled, postponed, or redirected at any level of granularity.

Noted. I'll add this to the description.

> We do support this, we just consider it bad practice to hard-code it to the link itself. 

Will update.

> The alpha version allows specification of different 'policies' for this.

Will update.

> This use case is covered by parameter observers. Combined with type definitions (i.e.Book in your example), you can encapsulate resource loading and data updating in a much more focused way than is possible with an arbitrary hook.

I'll have to research this more – I'm intrigued!

**Comment by nateabele** [comment]
> [T]hanks so much for going through this huge doc! I really appreciate it.

You bet. I'll definitely keep an eye on your work here. I've been meaning to get back to you on that conversation we had, too. Route sorting has come up a few times in our 1.0 refactor discussions. I just want to get the work we have pending out the door before I take anything else up.

> Is it the curly braces that mark it as optional? I wasn't able to discern this behavior based on the API docs on the website, which state the following facts:

It's doc'd here: https://angular-ui.github.io/ui-router/site/#/api/ui.router.state.$stateProvider#methods_state (see the `params` object). What the test is showing is that a `URLMatcher` definition with a `params` object that sets the default value of a parameter makes that parameter optional.

> Though, maybe you're right that it makes more sense to give it a check with an asterisk, since it's not like you need to bring your own history to work with UI-Router. I'll make the change.

Yeah, the question itself doesn't really make sense in the context of UI-Router, since you'd only ever use it with Angular.

> I'll have to research this more – I'm intrigued!

Yeah, I'm pretty happy with how it's turned out. You can read a bit about it here: https://angular-ui.github.io/ui-router/site/#/api/ui.router.util.$urlMatcherFactory#methods_type

**Comment by jamesplease** [comment]
I think all of the points in the original issue have been updated in the doc. Thanks again, @nateabele !
